import './ResultsSection.css'
import VideoPlayer from './VideoPlayer'

function ResultsSection({ veoResult, veoError, klingResult, klingError, onReset }) {
  return (
    <div className="results-section active">
      <div className="dual-video-container">
        {/* Google Veo Video */}
        <div className="single-video-result">
          <h3 className="video-result-title">Video generated by Google Veo</h3>
          {veoError ? (
            <div className="result-card error">
              <div className="result-message">{veoError}</div>
            </div>
          ) : veoResult?.videoUrl ? (
            <div className="result-card">
              <VideoPlayer videoUrl={veoResult.videoUrl} />
            </div>
          ) : (
            <div className="result-card loading">
              <div className="loading-spinner"></div>
              <div className="result-message">Generating video...</div>
            </div>
          )}
        </div>

        {/* Kling Video */}
        <div className="single-video-result">
          <h3 className="video-result-title">Video generated by Kling</h3>
          {klingError ? (
            <div className="result-card error">
              <div className="result-message">{klingError}</div>
            </div>
          ) : klingResult?.videoUrl ? (
            <div className="result-card">
              <VideoPlayer videoUrl={klingResult.videoUrl} />
            </div>
          ) : (
            <div className="result-card loading">
              <div className="loading-spinner"></div>
              <div className="result-message">Generating video...</div>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}

export default ResultsSection

